sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hsu_isaac/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hsu_isaac/docker-react npm run test
