name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true cygnetops/react-test npm test

      - name: Debugging information before zip
        run: |
          pwd
          ls -la
          
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x 'node_modules*'
        
      - name: Debugging information after zip
        run: |
          ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debugging information before deployment
        run: |
          pwd
          ls -la
          
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-west-1-188358956076
          region: us-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          
      - name: Debugging information after deployment
        run: |
          ls -la
